### PR TITLE
Rework entity creation

### PR DESCRIPTION
**Pull request by abretaud**
I had some warnings when installing this module, so I tried to fix it, using tripal_analysis_blast as model

### CODE REVIEW

**Comment by abretaud** [comment]
oops... seems like i failed syncing the code at some point, I'll look into it

**Comment by bradfordcondon** [comment]
I will try to add some CI to this module to make sure its installing properly on our travis set up at least.

**Comment by spficklin** [comment]
Hi @abretaud I believe you and I must have both fixed this at the same time which I think is the cause of the merge conflict.

**Comment by abretaud** [comment]
Ah, funny!
So here's a fix for a last `Undefined variable` warning

**Comment by abretaud** [comment]
Would it be possible to merge this if you have 2 minutes?

**Comment by bradfordcondon** [comment]
@spficklin is out of town ill get to this today now that i have admin rights on this repo.

**Comment by abretaud** [comment]
ok, no problem, thanks!

**Comment by bradfordcondon** [comment]
i dont get this error on enabling the module and creating hte content type.  However its an obvious PR since its not using a job and the defualt value in the call is NULL, so i will approve.  thank you @abretaud and sorry to make you wait.

**Pull request merged**
